title: TypeScript Libraries
description: System Core Library - contains runtime, reflection, and primitives
author: © TypeScriptLibs
email: bug@typescriptlibs.org
github_username: typescriptlibs
rss: rss

show_excerpts: false

github:
    private: true

header_pages:
 - index.md
 - libraries.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

minima:
  date_format: "%Y-%m-%d"
